#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: Shreyash Yadav | Course: Open Source Software

# Quick Concept: Aliases
# You can create a shortcut for this script by adding this to your ~/.bashrc:
# alias manifesto='bash script5.sh'

clear
echo "--- Personal FOSS Manifesto Generator ---"
echo "Answer these 3 quick questions to build your statement."
echo ""

# Taking user input
read -p "1. What is one open-source tool you couldn't live without? " TOOL
read -p "2. In just one word , what does 'Digital Freedom' mean to you? " FREEDOM
read -p "3. If you could build and share one thing for free, what would it be? " BUILD

# Setting up variables
DATE=$(date '+%d %B %Y')
OUTPUT="manifesto_$(whoami).txt"

# Generating the humanized manifesto
echo "--- MY OPEN SOURCE MANIFESTO ---" > "$OUTPUT"
echo "Generated by: $(whoami) on $DATE" >> "$OUTPUT"
echo "------------------------------------------------" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "I believe that technology works best when it's transparent and shared.
Every single day, I rely on tools like $TOOL—" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "To me, software is about more than just code; it is about $FREEDOM.
It’s the right to know exactly what is happening in
the machines we use every day." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "My goal is to give back to this ecosystem by building $BUILD
and releasing it openly" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "------------------------------------------------" >> "$OUTPUT"

echo ""
echo "Done! Your manifesto has been saved to: $OUTPUT"
echo "Reading back your statement now..."
echo ""
# Display the final result
cat "$OUTPUT"
